[package]
name = "aviutl2_calc"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
aviutl2 = { version = "0.16", features = ["generic"] }
image = { version = "0.24", features = ["png"] }
aviutl2-eframe = "0.16" 
log = "0.4"
anyhow = "1"